apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: demo-service
  title: Demo Service
  description: Scaffold a demo service
spec:
  owner: devops
  type: service

  parameters:
    - title: Service Info
      required:
        - name
      properties:
        name:
          title: Service name
          type: string
          description: Unique name of the service

    - title: Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch
      name: Fetch template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
