apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
    owasp.org/dependency-check-report: https://${{ values.destination.owner }}.github.io/${{ values.destination.repo }}/owasp/dependency-check-report.html
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.namespace | default("default") }}
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner }}
