apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
    backstage.io/github-actions-id: ${{ values.destination.owner }}/${{ values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - express
    - typescript
    - api
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | default("group:default/DevOps") }}
  providesApis:
    - ${{ values.name }}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}-api
  description: REST API for ${{ values.name }}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.owner | default("group:default/DevOps") }}
  definition: |
    openapi: 3.0.0
    info:
      title: ${{ values.name }}
      version: 1.0.0
    paths:
      /health:
        get:
          summary: Health check
          responses:
            '200':
              description: Service is healthy
